### ISSUE TITLE
Array of Labels and their text 

### ISSUE THREAD

**Issue by Joebeazelman** [adamws/kle-serial#23]
Awesome tool!  The conversion works almost flawlessly with the exception of one issue.  For the first key, there are only five (5) entries in the labels field while it's nine for all the other keys. I've enclosed the entire file for your review.

```
"keys": [
    {
      "color": "#413c2c",
      "labels": [
        null,
        null,
        null,
        null,
        "←"
      ],
      "textColor": [
        null,
        null,
        null,
        null,
        null
      ],
      "textSize": [],
      "default": {
        "textColor": "#f1ecda",
        "textSize": 7
      }
...
     {
      "color": "#413c2c",
      "labels": [
        null,
        "!",
        null,
        null,
        null,
        null,
        null,
        "1",
        null,
        null,
        "BLK"
      ],
      "textColor": [
        null,
        null,
        null,
        null,
        null
      ],
```
[vic20-layout.json.zip](https://github.com/adamws/kle-serial/files/9872928/vic20-layout.json.zip)

**Comment by adamws** [comment]
Thanks for reporting, I checked and it looks like that is how `ijprest/kle-serial` implements it. Right now I'm not considering patching that.
